batch_size: 1
workers: 5
nepoch: 100
model_name: cascade
load_model: "/root/shenzhen_1_1/zmh/point_cloud_jsen/PCUNet/cascade_log/cascade_cd_debug_2022-02-21T19:06:36/best_cd_t_network.pth"
#  "/root/shenzhen_1_1/zmh/point_cloud_jsen/PCUNet/cascade_log/cascade_cd_debug_2022-01-25T22:41:56/best_cd_t_network.pth"
start_epoch: 0
num_points: 2048
work_dir: cascade_log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: True
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

# test
save_vis: False