batch_size: 32
workers: 3
nepoch: 100
model_name: pcn
load_model:
#  "/root/shenzhen/zmh/point_cloud/PCUNet/pcn_log/pcn_cd_debug_2021-09-16T09:08:27/best_cd_t_network.pth"
#  "/root/shenzhen/zmh/point_cloud/PCUNet/pcn_log/pcn_cd_debug_2021-09-03T06:26:39/best_cd_t_network.pth"
start_epoch: 0
num_points: 2048
work_dir: pcn_log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

# test
save_vis: False